name: build

on: [push, pull_request]

jobs:

  linux:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [g++, clang++]
        mode: [-DBUILD_UVW_LIBS=ON, -DBUILD_UVW_LIBS=OFF]

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      working-directory: build
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        cmake ${{ matrix.mode }} -DBUILD_TESTING=ON -Dlibuv_buildtests=OFF ..
        make -j2
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 5 -C Debug -j2

  linux-native-libuv:
    timeout-minutes: 60

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests (${{ matrix.os }} system libuv)
      working-directory: build
      run: |
        sudo apt-get -o=Dpkg::Use-Pty=0 -qy install libuv1-dev
        cmake -DBUILD_UVW_LIBS=ON -DFETCH_LIBUV=OFF -DBUILD_TESTING=ON ..
        make -j2
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 5 -C Debug -j2

  windows:
    timeout-minutes: 60
    runs-on: windows-latest

    strategy:
      matrix:
        generator: [Visual Studio 16 2019]
        mode: [-DBUILD_UVW_LIBS=ON, -DBUILD_UVW_LIBS=OFF]

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      working-directory: build
      run: |
        cmake ${{ matrix.mode }} -DBUILD_TESTING=ON -Dlibuv_buildtests=OFF -DCMAKE_CXX_FLAGS=/W1 -G"${{ matrix.generator }}" ..
        cmake --build . -j 2

  macos:
    timeout-minutes: 60
    runs-on: macOS-latest

    strategy:
      matrix:
        mode: [-DBUILD_UVW_LIBS=ON, -DBUILD_UVW_LIBS=OFF]

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      working-directory: build
      run: |
        cmake ${{ matrix.mode }} -DBUILD_TESTING=ON -Dlibuv_buildtests=OFF ..
        make -j2
